= Development Log = 

== 2025-04-17 ==

The project will contain not only parts which are directly connected to the KratOS, but also it will include the 'exercises' that I do in order to obtain specific skills for the project. Thus the development history will be presented in flash as well as, maybe it will show future me and someone interested how you should and shouldn't (probably the last one will prevail) do your OS development project.

Also I had some thoughts on what initial goal/future plans are for my KratOS. It's important, I think, to make goals, which will not block the development. I mean, I should not hope to create the best OS ever, or beat the existing mastodons of the sphere, but it's far worse tp think that my job is a dead end and will end up in a read repository unseen by anybody. I hope, everything I do will find its users, and by now I will just try to do my job the best way, as if I am doing the bet OS ever, and we wiil se what comes next. 

== 2025-03-17 ==

I will try to build an ARM-focuced OS, which will has 64-bit register size.
The next step is to understand what difficulties and tasks lie in this field.

== 2025-02-27 ==

Devlogs are now here, the https://github.com/GrindelfP/kratos/blob/main/README.adoc[README] should contain clean information on the project.
  
== 2025-02-26 == 
  
The name will be KratOS. It sounds better. 
  
== 2025-02-24 == 

I am quite foggy about what this OS will look like and what it will be able to do, but still I have following expectations:

1. KratosOS will be a terminal-based OS. Maybe I will make a GUI (Graphical User Interface) but that is highly unlikely.
2. It should have functionality to boot up, execute basic programs (text editor at least) and support file system. 
3. The input will be done mainly by keyboard, maybe mouse will be supported but that is also highly unlikely.
4. The output is done to the display. 

Of course these requirements are quite vague and maybe wrong a little, but I want to state here my expectations at the moment when I start the project.

*IMPORTANT* Decide, whether the name will be KratOS or still Kratos.
